server:
  port: 9001

spring:
  application:
    name: banking-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

hystrix:
  dashboard:
    proxyStreamAllowList: '*'

application:
  customer-service:
    endpoints:
      url: http://localhost:9002/customer
  loan-service:
    endpoints:
      url: http://localhost:9003/loan