server:
  port: 9001

spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: banking-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

application:
  customer-service:
    endpoints:
      url: http://localhost:9002/customer
  loan-service:
    endpoints:
      url: http://localhost:9003/loan

logging:
  file: _logs/app.log