DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  ACCOUNT_NO BIGINT NOT NULL,
  BALANCE DOUBLE NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  EMAIL_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY ( ID )
);