server:
  port: 9001

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banking?createDatabaseIfNotExist=true&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: banking-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

application:
  customer-service:
    endpoints:
      url: http://localhost:9004/customer
  loan-service:
    endpoints:
      url: http://localhost:9004/loan