server:
  port: 9002

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer?createDatabaseIfNotExist=true&useSSL=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: customer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

logging:
  file: _logs/app.log