DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(50) NOT NULL,
  ACCOUNT_NO INT NOT NULL,
  BALANCE NUMERIC(20, 2) NOT NULL,
  PHONE VARCHAR(12) NOT NULL,
  EMAIL_ID VARCHAR(50) NOT NULL,
  PRIMARY KEY ( ID )
);