server:
  port: 9003

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: account
  application:
    name: loan-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

customer-service:
  endpoints:
    url: http://localhost:9002/customer