server:
  port: 9003

spring:
  zipkin:
    base-url: http://localhost:9411/
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:loan;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  application:
    name: loan-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true

customer-service:
  endpoints:
    url: http://localhost:9002/customer

logging:
  file: _logs/app.log