server:
  port: 9001

spring:
  application:
    name: banking-service

customer-service:
  endpoints:
    url: http://localhost:9002/customer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    preferIpAddress: true