server:
  port: 9004

spring:
  application:
    name: gateway-service

zuul:
  routes:
    banking-service:
      path: /account/**
      serviceId: banking-service
    customer-service:
      path: /customer/**
      serviceId: customer-service
    loan-service:
      path: /loan/**
      serviceId: loan-service

ribbon:
  ReadTimeout: 60000
  eureka:
    enabled: true

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka