spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:banking;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

customer-service:
  ribbon:
    eureka:
      enabled: true
    #listOfServers: localhost:9002,localhost:9003,localhost:9004
    ServerListRefreshInterval: 2000