server:
  port: 9001

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driverClassName: oracle.jdbc.OracleDriver
    username: SYSTEM
    password: xxxxxx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
  application:
    name: banking-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true

logging:
  file: _logs/app.log