server:
  port: 9003

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arun-stephen/microservice-remote-config
          search-paths:
            - '*service'
  application:
    name: config-server